### ISSUE TITLE
Target API SubRegIndexType not general enough for X86

### ISSUE THREAD

**Issue by matsc-at-sics-se** [matsc-at-sics-se/unison#1]
uni import may encounter subreg specifiers that are more general than a single (low) or (hi).
Consequently chains of (low)/(hi) may be required in some cases:

    COPY %13:sub_16bit: low 16 bits out of 32/64: either (low) or (low) + (low)

    COPY %13:sub_8bit: low 8 bits out of 16/32/64: either (low) or (low) + (low) or (low) + (low) + (low)

    COPY %13:sub_8bit_hi: 2nd lowest 8 bits out of 16/32/64: either (high) or (low) + (high) or (low) + (low) + (high)

So, generalize the target API, or intercept these things upstream somehow?

**Comment by robcasloz** [comment]
Could you attach a MIR function where you encounter these cases?

**Comment by matsc-at-sics-se** [comment]
I only encountered one of the cases, see attached, but I would expect the other ones too.


*.mir:

    %58 = COPY %57:sub_8bit

*.uni:

    o23: [t25] <- (low) [t24] // WRONG: t24 is 32 bits, t25 is 8 bits

Do you think that it could/should be fixed as a peephole transformation in Unison.Target.X86.Transforms?


Mats Carlsson

RISE SICS

https://www.sics.se/people/mats-carlsson

________________________________

**Comment by robcasloz** [comment]
I cannot find any attachment, perhaps it was lost if you replied via email?

**Comment by matsc-at-sics-se** [comment]
Right, sorry, I'm not Github savvy.
[cnv_encd.zip](https://github.com/matsc-at-sics-se/unison/files/1764856/cnv_encd.zip)

**Comment by robcasloz** [comment]
Commit 1b2d335 points to this issue by mistake, it is unrelated.

**Comment by matsc-at-sics-se** [comment]
Commit `425e74e4c2796b997dc14ae6de023d213bfe4dca` closes this.
