### ISSUE TITLE
stack frames, frame indices, conversions

### ISSUE THREAD

**Issue by matsc-at-sics-se** [matsc-at-sics-se/unison#14]
This is a discussion issue.

Consider this fragment from a *.mir:
```
name:            save_relocate_predicate
[...]
stack:           
  - { id: 0, name: record, offset: 0, size: 72, alignment: 8 }
[...]
    MOV64mr %stack.0.record, 1, _, 8, _, %5, <0x504f240> = !{!"unison-memory-partition", i32 0} :: (store 8 into %ir.24)
[...]
```
Recall that MOV64mr is a register-to-memory move instruction taking an X86 memory operand and a register operand, the X86 memory operand being the struct:
```
    [%stack.0.record, 1, _, 8, _]
```
meaning "offset 8 off %stack.0.record".

As far as I understand from our discussion the other day, %stack.0.record stands for:
```
    (Bound MachineFrameIndex {mfiIndex = 0, mfiOffset = 0})
```
The problem is that the instruction description requires the first field of the struct to be a register, not a bound, so it needs to be converted by uni import.  I have such a conversion now, turning it to:
```
    [rsp, 1, _, 8, _]
```
i.e. getting rid of the fram index altogether. Now, I'm afraid that this is the wrong solution, given the relocation magic that uni export needs to do.  So I have two alternative ideas:

**Idea 1**

uni import turns it into something like:
```
    [_, 1, _, %stack.0.record.plus.8, _]
```
where "%stack.0.record.plus.8" is a new frame index, created on the fly, pointing inside stack.0.record.  So the Haskell representation would be:
```
    (Bound MachineFrameIndex {mfiIndex = 1, mfiOffset = 8})
```
and there would be two items under the "stack:" heading:
```
stack:           
  - { id: 0, name: record, offset: 0, size: 72, alignment: 8 }
  - { id: 1, name: record.plus.8, offset: 8, size: 8, alignment: 8 }
```
where id 1 **overlaps** id 0.

Is that a feasible solution, or are overlapping frame indices a show-stopper?

**Idea 2**

Add a second offset field to MachineFrameIndex, like so:
```
  MachineFrameIndex {
    mfiIndex  :: Integer,
    mfiFixed  :: Bool,
    mfiOffset :: Integer
    mfiSubOffset :: Integer
    } |
```
(and maybe to MachineFrameObject, I don't know).

uni import turns it into something like:
```
    [_, 1, _, %stack.0.record.plus.8, _]
```
where "%stack.0.record.plus.8" uses that mfiSubOffset field.  So the Haskell representation would be:
```
    (Bound MachineFrameIndex {mfiIndex = 0, mfiOffset = 0, mfiSubOffset = 8})
```
No extra item under the "stack:" heading would be needed.

Is that a feasible idea?

**Comment by matsc-at-sics-se** [comment]
**Idea 3**

Could we introduce a new operand type, essentially a "register view" (stack pointer + offset), to be treated as a register?  (MachineOperand r) is typically a frame index:
```
data operand r = 
    [...]
    -- | Frame pointer, later to be turned into stack ptr register + offset
    FramePointer (MachineOperand r) |
    [...]
```
Then uni import would just have to change the "tag" of the frame index (1st element of the memory operand tuple) from Bound to FramePointer.
The code that typechecks operands would treat FramePointer as the stack pointer.
Various case analysis on operands would also need to be augmented.
This is perhaps the simplest solution?

**Comment by robcasloz** [comment]
Hi, good that you bring this up! There is a mismatch between LLVM's MIR and Unison IR when it comes to representing SP-relative locations (`MO_FrameIndex` in MIR, `MachineFrameIndex` in Unison IR). LLVM's MIR allows instructions to contain `MO_FrameIndex` operands where register operands are expected, Unison IR does not allow a `MachineFrameIndex` if a register operand is expected. Currently, different Unison targets work this out by defining instruction versions (typically suffixed with `_fi`) with frame index operands and making the conversion at `preProcess` and `postProcess` time. This can be very painful for a target where many instructions might perform SP-relative accesses.

From the three ideas you propose I like 3 the most as it is the closest to LLVM's representation. But why not pushing it a step further and just letting Unison accept operands of the form `Bound MachineFrameIndex` when registers are expected? The advantage is that we do not need to duplicate the machine frame index operand type for the Unison IR level, and we can handle them similarly to null registers (`_`) which are represented by `Bound MachineNullReg`. Would you like to give this a try? Just relax the checks in `Invariants.hs` and see what else (if anything) needs to be patched.

**Comment by matsc-at-sics-se** [comment]
I agree to the plan to "push it a step further".
The suggested fix to `Invariants.hs` works fine! Two functions needed amending: `consistentOperand` and `consistentSingleOperandInfo`.

Keeping issue open, it is bound to be continued.

**Comment by matsc-at-sics-se** [comment]
Related to this, I implemented an `ExportPreLow` transform, `myLowerFrameIndices`, which supersedes the generic `lowerFrameIndices`, adding `FrameSize` to every `FrameIndex` "register". It sort of works, but `FrameSize` is often not normalized (should be 8*n, where n must be odd in the presence of recursive calls).
Closing this issue. To be continued in another issue.
