### ISSUE TITLE
Avoid using tail call arguments in (out) operations

### ISSUE THREAD

**Issue by robcasloz** [matsc-at-sics-se/unison#37]
Here is a deviation between `--explicitcallregs` and the old scheme. It's about tail-recursive call.

A fragment from the old scheme, `gcc.cpplib._cpp_init_internal_pragmas` for ARM:
```
[...]
    o49: [] <- tTAILJMPdND [@cpp_register_pragma,14,_] (reads: [control,sp])
    o50: [] <- (fun) [p113{t0, t11, t18, t27, t34, t43, t50}:r0,p114{t32, t33, t37, t44, t51}:r1,p115{t48}:r2,p116{t49}:r3] (writes: [control,pc], call: o49)
    o51: [] <- (out) [p117{t1, t7, t53}:r4_7,p118{t2, t8, t54}:r8_11,p119{t3, t10, t52}:d8_15,p120{t4}:sp,p121{t5}:lr,p122{t6}:pc]
```
Note that the `(fun)` operand are distinct from the `(out)` ones.
A fragment from the new scheme, `aainsert` for X86:
```
[...]
    o97: [] <- TCRETURNdi64 [@aasplit,0] (reads: [control,rsp])                                                                                               
    o98: [] <- (fun) [p297{t133, t140, t141, t148}:rdi] (writes: [control,pc,eflags], call: o97)                                                              
    o99: [] <- (out) [p298{t123,t142}:rbx,p299{t124,t143}:rbp,p300{t125,t144}:r12,p301{t126,t145}:r13,p302{t127, t146}:r14,p303{t128, t147}:r15,p304{t129}:rsp,p305{t130}:rip,p306{t133, t140, t141, t148}:rdi]    
```
Note that the `(fun)` operand `p297` is repeated as the `(out)` operand `p306`.

This upset the presolver and caused loss of solutions.
A presolver work-around was pushed in commit `207b9093a4dcc461e6c6e06fc7b7f1fdce47f0a8`, but we need to agree on how it should be.

**Comment by robcasloz** [comment]
Here is how to reproduce it:
```
$ uni import -f aainsert aainsert.mir -o aainsert.uni --target=X86 --explicitcallreg --goal=speed --copyremat --lint
```
[aainsert.mir.zip](https://github.com/matsc-at-sics-se/unison/files/2079430/aainsert.mir.zip)

 I think that the presolver should tolerate the operand repetition (it does not violate any invariant of the Unison IR) but we should avoid generating such patterns for sanity and to reduce overhead.

**Comment by matsc-at-sics-se** [comment]
The presolver does tolerate that now.

Here is what LLVM seems to think about a minimal example:
```
body:             |
  bb.0 (%ir-block.0, freq 8):
    liveouts: %rsp, %edi
  
    %0 = MOV32ri 1
    %edi = COPY %0
    TCRETURNdi64 @spio_call_interrupt_hooks, 0, csr_64, implicit %rsp, implicit %edi
```
This becomes *.uni:
```
b0 (entry, exit, return, freq: 1):
    o0: [t0:rbx,t1:rbp,t2:r12,t3:r13,t4:r14,t5:r15,t6:rsp,t7:rip] <- (in) []
    o1: [] <- SUBRSP_pseudo [%frame-size]
    o2: [t8] <- MOV32ri [1]
    o3: [] <- ADDRSP_pseudo [%frame-size] (split-barrier)
    o4: [] <- TCRETURNdi64 [@spio_call_interrupt_hooks,0]
    o5: [] <- (fun) [t8:edi] (call: o4)
    o6: [] <- (out) [t0:rbx,t1:rbp,t2:r12,t3:r13,t4:r14,t5:r15,t6:rsp,t7:rip,t8:edi]
```
Note `liveouts: %rsp, %edi`. This suggests that Unison too should consider `%edi` a live out. So maybe we should leave it as is. Closing the issue for now.
