### ISSUE TITLE
uni model: way too slow

### ISSUE THREAD

**Issue by matsc-at-sics-se** [matsc-at-sics-se/unison#50]
[gobmk.combination.atari_atari_attack_callback.zip](https://github.com/matsc-at-sics-se/unison/files/2166099/gobmk.combination.atari_atari_attack_callback.zip)

```
$ uni model --target=X86 --basefile=gobmk.combination.atari_atari_attack_callback.llvm.mir gobmk.combination.atari_atari_attack_callback.alt.uni -o gobmk.combination.atari_atari_attack_callback.json  
```
This takes > 10 minutes, which is ridiculous.

**Comment by robcasloz** [comment]
Commit 51cf2ba8ebddfef4e8acf1688c20977e1f2ebd9c reduces the runtime to less than a minute. The example has a huge number of register atoms, which might create other bottlenecks in later parts of the toolchain.
