### ISSUE TITLE
Distance ad-hoc constraint involving operations from different blocks makes gecode-solver crash

### ISSUE THREAD

**Issue by robcasloz** [matsc-at-sics-se/unison#54]
When running the command `uni model --target=X86` on 
[gcc.attribs.handle_noinline_attribute.alt.uni.txt](https://github.com/matsc-at-sics-se/unison/files/2255207/gcc.attribs.handle_noinline_attribute.alt.uni.txt) the ad-hoc distance constraint `[8, 59, 27,-1]` is generated, which is invalid as o27 and o59 belong to different basic blocks.

The issue originates from the function `indicatorConstraints` in `X86.hs` where `blockIns` and `blockInfo` are zipped although they do not have the same length. I could not fix it as I do not fully understand the meaning of these ad-hoc constraints.

The issue crashes `gecode-solver` for many of the experiment instances.

**Comment by matsc-at-sics-se** [comment]
Oh my. Will address it on Monday.

**Comment by matsc-at-sics-se** [comment]
Closed by commit e387485.
