### ISSUE TITLE
uni import: "PHI undef %..." apparently causes bug

### ISSUE THREAD

**Issue by matsc-at-sics-se** [matsc-at-sics-se/unison#56]
Reproducer:
```
uni import l1_phy_crc.mir -o l1_phy_crc.uni --llvm6 --explicitcallregs --lint
uni linearize l1_phy_crc.uni -o l1_phy_crc.lssa.uni --lint
allEntryOpsPreAssigned: the entry operand t10 is not pre-assigned
allEntryOpsPreAssigned: the entry operand t11 is not pre-assigned
```
The trouble seems to stem from the undef temps mentioned on these lines in `l1_phy_crc.mir`:
```
    %24:vr128 = PHI undef %60:vr128, %bb.5, %17, %bb.8
    %25:vr128 = PHI undef %61:vr128, %bb.5, %18, %bb.8
```
[l1_phy_crc.zip](https://github.com/matsc-at-sics-se/unison/files/2851696/l1_phy_crc.zip)

**Comment by robcasloz** [comment]
Sorry, cannot reproduce it:
```
uni import l1_phy_crc.mir -o l1_phy_crc.uni --llvm6 --explicitcallregs --lint
uni: unmatched: readOp "VPALIGNRrri"
```
Perhaps you have some local changes to be pushed?

**Comment by matsc-at-sics-se** [comment]
```
matsc@teterev:~/unison$ git status
On branch llvm-trunk
Untracked files:
  (use "git add <file>..." to include in what will be committed)
[...]
```
So I'm on the llvm-trunk branch, which I guess lives on my computer only.
Can you tell me what to type to create such a branch on Github?

It would be good to be able to compile this function to get one more data point for Ericsson. I only have seven or so AVX-style functions to base results and conclusions on.

**Comment by robcasloz** [comment]
Reopening as the issue is still present.
